fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Flake8
        entry: poetry run flake8 --max-line-length=120
        pass_filenames: false
        language: system
